import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './lib/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-primary':                '#ffffff',
        'on-tertiary-fixed':         '#001e2f',
        'surface-container-high':    '#e6e8ea',
        'primary-fixed-dim':         '#b8c4ff',
        'surface-container-low':     '#f2f4f6',
        'on-secondary-fixed-variant':'#38485d',
        'on-secondary-fixed':        '#0b1c30',
        'on-primary-fixed-variant':  '#173bab',
        'inverse-primary':           '#b8c4ff',
        'surface-bright':            '#f7f9fb',
        'on-secondary-container':    '#54647a',
        'outline':                   '#737686',
        'primary-container':         '#4865d3',
        'surface-container':         '#eceef0',
        'surface-container-lowest':  '#ffffff',
        'secondary-fixed-dim':       '#b7c8e1',
        'primary-fixed':             '#dde1ff',
        'on-error-container':        '#93000a',
        'primary':                   '#2b4bb9',
        'outline-variant':           '#c3c6d7',
        'surface-container-highest': '#e0e3e5',
        'on-primary-container':      '#efefff',
        'on-secondary':              '#ffffff',
        'tertiary-fixed-dim':        '#89ceff',
        'tertiary-fixed':            '#c9e6ff',
        'secondary-container':       '#d0e1fb',
        'inverse-on-surface':        '#eff1f3',
        'tertiary':                  '#005a82',
        'on-tertiary':               '#ffffff',
        'on-primary-fixed':          '#001453',
        'on-tertiary-fixed-variant': '#004c6e',
        'tertiary-container':        '#0074a6',
        'on-tertiary-container':     '#e4f2ff',
        'error':                     '#ba1a1a',
        'on-surface-variant':        '#434655',
        'background':                '#f7f9fb',
        'surface':                   '#f7f9fb',
        'surface-tint':              '#3755c3',
        'surface-dim':               '#d8dadc',
        'on-error':                  '#ffffff',
        'error-container':           '#ffdad6',
        'secondary-fixed':           '#d3e4fe',
        'on-surface':                '#191c1e',
        'surface-variant':           '#e0e3e5',
        'on-background':             '#191c1e',
        'secondary':                 '#505f76',
        'inverse-surface':           '#2d3133',
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans', 'sans-serif'],
        body:     ['Inter', 'sans-serif'],
        label:    ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        '2xl':   '1.5rem',
        full:    '9999px',
      },
    },
  },
  plugins: [],
};

export default config;
